### ISSUE TITLE
Provide an option to force a gem version, even it it conflicts with a gem's declared compatibility.

### ISSUE THREAD

**Issue by lynncyrin** [rubygems/bundler#4552] opened 2016-05-09 21:27 UTC
_From @xaviershay on August 22, 2013 3:22_

From https://github.com/bundler/bundler/issues/2412

Still debate about how this would be done or whether it's a good idea. See linked ticket for context.

_Copied from original issue: bundler/bundler-features#20_

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @xaviershay on August 22, 2013 3:25_

Also this https://github.com/bundler/bundler/issues/1549

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @rmetzler on September 3, 2013 23:31_

Today I started to look into this.

I read about all proposals for the API. The DSL style I liked best and is the easiest to implement is the following notation:

    gem 'mail', '~> 2.4.4', :override => true

This notation means, that the resolver uses the version marked by the override option whenever two dependencies are compared.

**Requirements**

* Bundler should warn about this, because it is a potentially dangerous option.
* If Bundler compares two conflicting dependencies both having `:override => true` then Bundler should throw a special `VersionConflict` error.

### Questions

As I'm new to the Bundler source, trying to find my way around I recognized some minor issues. Also I'm not sure whether I should it ask here or on the mailing list. I'll just write it down here because it's easier now. Please advise!

1. I didn't found a test case for `Bundler::VersionConflict` so I [added one.](https://github.com/rmetzler/bundler/commit/054fe8e0e841f954dce6b1df27061dbf8f4a6a2e) It's modeled after a detailed description of the problem, but could be simpler though.

2. I found [this line](https://github.com/rmetzler/bundler/blob/master/spec/support/indexes.rb#L5) that doesn't look right, especially when you consider [this constructor](https://github.com/rmetzler/bundler/blob/master/lib/bundler/dependency.rb#L31). Not really sure about that, had a few errors when I changed it and run tests.

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @indirect on September 5, 2013 5:42_

I think that `:force_version => true` might make it clearer what the option does, since there are other options that could be passed as well, making `:override` a bit ambiguous (override what? and with what?).

I'm happy to merge a testcase for VersionConflict. :+1: Unit tests in general are a weak area for the Bundler codebase. :grimacing: 

The line you point to doesn't look right to me either, but maybe there's another `Bundler::Dependency` hiding somewhere?

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @rmetzler on September 5, 2013 9:3_

Thank you for you reply, very much appreciated. I also think `:force_version => true` is a clearer option.

I'll send a pull request for VersionConflict and investigate further in `dep` helper method.

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @sheerun on October 17, 2013 13:11_

I don't think it's good idea, forking is better solution.

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @rmetzler on October 17, 2013 14:46_

Hi,

first thing I've to say, I'm sorry I didn't send any pull request for the test cases yet.

@sheerun for discussing the proposed experimental feature in question please read over the discussion first here  https://github.com/bundler/bundler/issues/1549 and and https://github.com/bundler/bundler/issues/2412
I think this is the [best description for the current state of how they to fix gem dependency conflicts](https://github.com/bundler/bundler/issues/1549#issuecomment-3774196) 

I just want to fix the problem I encountered myself more than once. This feature would be experimental and so far I've not written anything else than tests, because the bundler code in question is fairly untested yet. Only "happy paths" were covered with tests in master branch and not conflicting dependency versions.

I also thought about writing a CLI tool (different from bundler) that would know about git, Github and Gemfiles and could do something like the [linked comment](https://github.com/bundler/bundler/issues/1549#issuecomment-3774196) suggested automatically incl running tests and send pull requests. If Ruby devs think this might be a better idea, please let me know.

Recently I also worked with VersionEye on their open source CLI [veye](https://github.com/versioneye/veye) and I realized that there are many issues around dependency versions. This is the case especially in Ruby and nodejs communities where the lib ecosystem is growing rapidly. But every package manager has this problem and if there are good solutions out there, please let me know and I'll investigate the code.

Richard

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @aantix on February 8, 2014 0:16_

:+1: Running into this very issue today.  I know the versions are compatible.  But one author has been too strict with his requirements..

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @korbin on March 11, 2014 20:12_

+1 for this feature.

Forking an entire project (and subsequently managing upstream changes, etc.) is an unnecessarily tall order for something that can certainly be fixed with a simple, at-your-own-risk dependency override.

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @indirect on March 11, 2014 21:24_

Again, the issue is not that we actively want to make it harder. The issue is that allowing this means there is no longer a canonical source of truth about what a gem’s dependencies are. When these kinds of changes cause resolver errors (and they will), it will be extremely hard to diagnose. I’m fine with “at your own risk”, I’m not fine with “makes people complain that Bundler is broken when it’s actually something they did themselves”.

If you’re competent enough to debug forcibly overridden dependencies yourself, you’re competent enough to either hack this feature into Bundler or fork and update the dependencies yourself. This feature hands a giant foot-gun to those who won’t know how to debug the issues that come up while using it.

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @TimMoore on March 11, 2014 22:9_

And think of the poor gem authors that will suddenly have a pile of mysterious bug reports caused by someone using a gem that was listed as explicitly incompatible!

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @strzibny on May 7, 2014 7:41_

I would also welcome this feature as this overly strict requirements are happening quite often. Providing an override option seems reasonable. Of course it's always on the risk of the user.

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @anri-asaturov on June 14, 2014 14:21_

This feature becomes more and more important with number of gems growing. .NET has it. Java has it. Nothing bad happened to them because of it.

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @indirect on June 28, 2014 4:16_

I’m slowly warming up to this, as long as the override is set explicitly in the gemfile on a line for the gem being overridden, and the overridden version is called out during `bundle install`. Something like:

```ruby
# Gemfile
gem "puma", "5.1" # depends on rack <= 2.0
gem "rack", "3.0", force_version: true
```

```bash
$ bundle install
[…]
Installing rack 3.0 (forced version, conflicts with puma)…
Installing puma 5.1…
[...]
```

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @thewoolleyman on November 18, 2014 5:20_

+1.

As mentioned on the [closed bug thread](https://github.com/bundler/bundler/issues/2412), one major exacerbating factor of this problem is that pessimistic constraints unnecessarily specify all three components of a semantic version, when they should only need to specify two to prevent API-incompatible changes in dependencies.

Rubygems.org unfortunately encourages this practice by always suggesting a pessimistic constraint with all three versions, which leads gem authors to do the same practice in their gemspecs.

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @TimMoore on November 18, 2014 5:53_

Maybe Rubygems.org should be changed to recommend setting only major and minor versions?

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @endymion on June 27, 2015 22:56_

I respectfully add my vote to this feature request.  Bundler's lack of a feature for forcing a version that's known to work has cost me hours of extra work today.  It's an even bigger issue when you're dealing with older Ruby code that uses gems where the authors have locked the dependencies to something like "~> 1.2.5" and then stopped maintaining a gem.  Sometimes a gem doesn't really need to be updated because it works, but it's still full of over-specific dependencies like that.  The only way to deal with it right now is to fork the gem itself and update the dependencies.  Bundler could easily have made my life a lot simpler today by giving me more flexibility and control and letting me take responsibility for my own QA.

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @indirect on June 28, 2015 19:47_

@endymion Thanks for the feedback. Today, no one on the Bundler core team has the time to do the work that this feature would involve. If someone joins the team who wants to implement and support the feature, or [Ruby Together](https://rubytogether) is willing to fund work on this feature, we'll take another look.

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @thewoolleyman on June 29, 2015 19:58_

@indirect I do agree with your previous comments that this could make the situation worse for Gem maintainers, because they don't know if a bug report is due to an incompatible overridden dependency version being used.

I still think the long-term solution is to encourage/force people to use pessimistic constraints correct.  E.g., docs on rubygems.org, and rubygems itself should complain loudly if you try to put a dependency version in a gemspec with a three-component pessimistic constraint, because in all likelihood You're Doing It Wrong.

Maybe someone (with more time and who cares more than me) can open that discussion on the RubyGems mailing list along these lines (and cross-link it here in a comment), and see what comes of that...

-- Chad

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @indirect on June 29, 2015 20:9_

The RubyGems.org pages have all changed to default to `~> X.Y` version constraints available for copying. I think it _might_ be worth it to warn if a gemspec has a pessimistic constraint on a bugfix release, but unfortunately there are many, many, many, gems that only function correctly at a precise bugfix release. :( It's a chicken and egg problem that I'm not sure how to progress on.

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @jfinkhaeuser on July 1, 2015 13:37_

If a gem has a constraint on a specific bugfix release because that's the only version it works with, that's a bug in the dependency.

Or, to go by example:
- Gem A exists in version 0.1.1
- Gem B requires precisely version 0.1.1, because it doesn't work with version 0.1.0

Then Gem A uses semantic versioning wrong. That cannot be emphasised enough.

The point of semantic versioning is to provide a stable interface across all releases with the same major and minor component. A bugfix that breaks the interface is simply no longer compatible with the same major and minor component.

Penalizing Gem B for doing the only thing left for it to do seems like entirely the wrong approach.

Gem B should specify dependencies as `~> 0.1 >=0.1.1` in this case. Being helpful about this would IMHO be a good feature.

But really, it's the Gem A maintainers that need to be given a hard time, not anyone else.

(Mind you, there is no easy solution to this. The best solution so far is to differentiate between interface and package versions, and depend on an interface version. That's happening to a degree in Linux/Solaris shared object libraries, and vastly improves some issues, but it's not bullet proof either.)

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @booleanbetrayal on October 30, 2015 15:14_

would definitely find this feature useful!

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @xeger on November 13, 2015 17:10_

I deal with a lot of abandonware gems whose authors never learned to manage dependencies correctly. I get bit by falsely-rigid constraints several times per year, preventing me from fixing security or functional defects in my _own_ software. I solve these by forking the offending gem and fixing the constraint.

Once in a very great while I find that there was a genuine reason for the author to be so pedantic. Generally, however, they were just ignorant about the pessimistic versioning notation. I fix the constraints, open a futile pull request in case the author ever wakes up again, and add a tech-debt item to stop depending on the offending gem.

Needless to say, I would find this feature _very_ helpful. That having been said, there's almost always a workaround -- forking the gem and depending on it as gitted, or pulling from a custom source -- so I understand the core team's unwillingness to spend precious cycles on the feature.

Nevertheless, I'd love to see a feature like this emerge! It would save me significant time in the long run. So, err, +1, and perhaps I'll spend some time implementing it, if I become seriously blocked.

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @todd-richmond on November 13, 2015 17:28_

very well put - thx! That is the exact issue we had... small, but highly useful gems that have been abandoned by their author with restrictions they didn't fully understand before going dark. In this case forking is a pain because we have to manage them and if the author ever does make changes, we probably won't notice

This is somewhat similar to maven's ability to exclude package dependencies so that you can enable the use of newer packages. The developer is owning the conflicts at that point so a warning would be fine, but far better than having to fork and hack

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @vbabu75 on December 29, 2015 11:28_

+1

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @jirihradil on January 19, 2016 20:15_

+1

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @teadur on February 3, 2016 10:14_

+1

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @Maxim-Gurin on March 15, 2016 15:42_

+1

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @egormasalitin on March 15, 2016 15:43_

+1

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @anton-fedorov on March 15, 2016 15:43_

+1

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @oleksandr-oksenenko on March 15, 2016 15:43_

+1

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @yuliiakorzhuk on March 15, 2016 15:43_

+1

**Comment by LynnCo** [comment] 2016-05-09 21:27
_From @batytskyy on March 15, 2016 15:43_

+1

**Comment by LynnCo** [comment] 2016-05-09 21:28
_From @asukhorukova on March 15, 2016 15:43_

+1

**Comment by LynnCo** [comment] 2016-05-09 21:28
_From @andreiiarnautov on March 15, 2016 15:44_

+1

**Comment by LynnCo** [comment] 2016-05-09 21:28
_From @a-paschenko on March 15, 2016 15:44_

+1

**Comment by thewoolleyman** [comment] 2016-05-10 00:00
@LynnCo Thanks for cleaning up.  Are there plans to implement a feature to address this, or are you just consolidating the tickets?

**Comment by segiddins** [comment] 2016-05-10 00:05
Just consolidating at the moment

**Comment by ioquatix** [comment] 2016-10-09 09:18
I'd like to add to this proposal.

In some cases, you can write like this:

```
gem "foo", git: "path/to/fork"
```

In some cases it would be useful to actually have a fork released as a gem, but replace all instances of it in the Gemfile and related dependencies.

```
gem "foo", provided_by: "foo-fork"
```

Where `foo-fork` is a gem which provides the same API (e.g. forked) as `foo`.

**Comment by cefigueiredo** [comment] 2017-01-20 19:47
I'd also like to add to this proposal... I got a case where I need to run an legacy app, that I'm not able to upgrade yet...
The problem is that a required gem that I don't maintain, depends on nokogiri, but was too soft to declare that... declaring just that depends on`nokogiri (>= 1.4.4)`

When the app was made, there were no problem with that... but today, nokogiri last version is 1.7.0.1 and requires a ruby version newer than exists on the environment.

Today ruby version is 2.0.0, so I must update it already... but it would be really helpful have the ability to force the version I know that works on my Gemfile for cases like that

**Comment by arcreative** [comment] 2017-02-13 22:12
As `:force_version => true` is clearly an opt-in change and extremely visible in a project's `Gemfile`, I'm finding the suggestion that one should fork every package a bit ridiculous.  

This request has very real use cases and is supported in most (all?) other major package managers.  The suggestion that every gem maintainer should change to minor versioning isn't a real solution, as there's a large coincidence of needing version overrides as a result of gems being abandoned.

What's the timeframe on this if it's agreed upon?

**Comment by ioquatix** [comment] 2017-02-13 22:14
@arcreative I think in order for bundler to make this improvement, it needs to be implemented in RubyGems first, per the linked issue.

**Comment by ms-ati** [comment] 2018-01-12 15:44
11 months later, what is the status of this feature request?

**Comment by segiddins** [comment] 2018-01-13 05:42
@ms-ati we have not even decided it is a feature we would like to implement (it needs a complete RFC first). Though I did toy around with the idea in https://github.com/bundler/bundler/pull/5670 just for fun

**Comment by arcreative** [comment] 2018-01-13 18:40
@segiddins Your PR looks simple enough, do you have any specific concerns about it?

**Comment by segiddins** [comment] 2018-01-15 19:49
The concern is that this is a feature with the potential to introduce _a lot_ of edge cases into bundler, and as such it needs to be well-planned out and considered before merging -- for a change like this, just a patch isn't enough.

**Comment by arcreative** [comment] 2018-01-15 20:30
I feel like it should be allowed for gemfiles, but not gemspecs.  That would mostly limit the implications of forcing versions to the end user when they opt into this behavior...right?  I agree it would be unpredicatable to have forced versions on dependencies of your project when it has other dependencies that may use the same gem, so maybe limiting the scope to gemfiles would be a happy medium?

**Comment by thewoolleyman** [comment] 2018-01-16 09:39
Yes, I agree it should only be for gemfiles and not gemspecs.  

@segiddens, would there still be many edge cases in this scenario?

If so, what are they? I can't think of many offhand.  It's a risk, but one solely incurred by the Gemfile's app itself, never imposed upon any dependent users of a published gem's gemspecs.

**Comment by ms-ati** [comment] 2018-01-16 19:23
@thewoolleyman I think you meant @segiddins (misspelled above)

**Comment by hswick** [comment] 2018-02-10 22:24
This feature would be nice :D

**Comment by rbq** [comment] 2018-03-24 12:05
Maybe instead of forcing versions in the Gemfile and considering this as a special case while resolving the dependencies we could find a way to overwrite the dependency information of a Gem locally (and not touch the whole resolution process at all)? Basically a way to patch a gemspec locally within a Gemfile? E. g. if you want to make Bundler act as if your old Rails version was compatible with a newer MySQL Gem:

````ruby
gem 'rails', '3.2.5' do |spec|
  spec.override_runtime_dependency 'mysql', '< 5.0.0'
end
```

(Disclaimer: Just an idea, didn't really think this through.)

**Comment by indirect** [comment] 2018-04-13 20:32
Thanks for the input, everyone.

Since this ticket isn't producing any new points for discussion, I'm going to lock it to collaborators until we have an RFC that discusses the tradeoffs involved and comes to conclusions about those tradeoffs that we can use as a basis for implementing something like this (or not, as the discussion goes).

**Closed** 2020-03-14 05:41 UTC
Labels: type: feature-request
