### ISSUE TITLE
config are stored to global when using `bundle config set --local` more than once

### ISSUE THREAD

**Issue by sue445** [rubygems/bundler#7610] opened 2020-01-28 15:38 UTC
# Actual
## case1
```
$ docker run --rm -it ruby:2.7 bash

root@854647daa75c:/# ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]

root@854647daa75c:/# bundle -v
Bundler version 2.1.2

root@854647daa75c:/# bundle config set --local path vendor/bundle

root@854647daa75c:/# cat .bundle/config
---
BUNDLE_PATH: "vendor/bundle"

root@854647daa75c:/# bundle config set --local clean 'true'

root@854647daa75c:/# cat .bundle/config
---
BUNDLE_PATH: "vendor/bundle"

root@854647daa75c:/# cat /usr/local/bundle/config
---
BUNDLE_CLEAN: "true"

root@854647daa75c:/# bundle config set --local without 'development test'

root@854647daa75c:/# cat /usr/local/bundle/config
---
BUNDLE_CLEAN: "true"
BUNDLE_WITHOUT: "development:test"
```

## case2
```
$ docker run --rm -it ruby:2.7 bash

root@013af2e10483:/# ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]

root@013af2e10483:/# bundle -v
Bundler version 2.1.2

root@013af2e10483:/# bundle config set --local clean 'true'

root@013af2e10483:/# cat .bundle/config
---
BUNDLE_CLEAN: "true"

root@013af2e10483:/# bundle config set --local path vendor/bundle

root@013af2e10483:/# cat .bundle/config
---
BUNDLE_CLEAN: "true"

root@013af2e10483:/# cat /usr/local/bundle/config
---
BUNDLE_PATH: "vendor/bundle"

root@013af2e10483:/# bundle config set --local without 'development test'

root@013af2e10483:/# cat .bundle/config
---
BUNDLE_CLEAN: "true"

root@013af2e10483:/# cat /usr/local/bundle/config
---
BUNDLE_PATH: "vendor/bundle"
BUNDLE_WITHOUT: "development:test"
```

# Expected
I expected all configs are stored to `.bundle/config` (not `/usr/local/bundle/config`).

# Supplement
* This behaviour is same to bundler v2.1.4 too

**Comment by deivid-rodriguez** [comment] 2020-02-02 16:37
Hi @sue445, thanks for reporting this issue in such a clear way.

The issue is specific to setting the `BUNDLE_APP_CONFIG` environment variable, like the docker images do, and should be fixed by the following patch:

```diff
diff --git a/lib/bundler.rb b/lib/bundler.rb
index df345539c8..3d8d951086 100644
--- a/lib/bundler.rb
+++ b/lib/bundler.rb
@@ -285,7 +285,13 @@ module Bundler
 
     def app_config_path
       if app_config = ENV["BUNDLE_APP_CONFIG"]
-        Pathname.new(app_config).expand_path(root)
+        app_config_pathname = Pathname.new(app_config)
+
+        if app_config_pathname.absolute?
+          app_config_pathname
+        else
+          app_config_pathame.expand_path(root)
+        end
       else
         root.join(".bundle")
       end
```

**Comment by deivid-rodriguez** [comment] 2020-02-02 18:23
By the way, the correct expectation here is that all configs are actually stored to `/usr/local/bundle/config`, because what `BUNDLE_APP_CONFIG` does is to change the location to the local configuration to the value set in there.

**Comment by deivid-rodriguez** [comment] 2020-02-03 15:31
#7622 should fix this!

**Closed** 2020-02-11 22:51 UTC
Labels: type: bug report
